name: Render Documentation as HTML and PDF

on:
  push:
    branches: [main]
    paths:
      - "doc/**"
      - ".github/workflows/SE.yml"

  workflow_dispatch:

jobs:
  vertical:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/qualityManager/"
          image_import: "../images/"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: false
          extend_default_theme: true
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/programming/"
          image_import: "../images/"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: false
          extend_default_theme: true
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/proxyUscrum/"
          image_import: "../images/"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: false
          extend_default_theme: true
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/tests/"
          image_import: "../images/"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: false
          extend_default_theme: true
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/usability/MockUp"
          image_import: "../images/"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: false
          extend_default_theme: true
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/usability/"
          image_import: "../images/"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: false
          extend_default_theme: true
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/"
          image_import: "../images/"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: false
          extend_default_theme: true
      - uses: actions/upload-artifact@v3
        with:
          name: "standard"
          path: "doc/Pdf/"
          
  landscape:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/querformat/"
          image_import: "../images/"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SEquerformat.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: false
          extend_default_theme: true
      - uses: actions/upload-artifact@v3
        with:
          name: "landscape"
          path: "doc/Pdf/"
