name: Render Documentation as HTML and PDF

on:
  push:
    branches: [main]
    paths:
      - "doc/**"
      - ".github/workflows/SE.yml"

  workflow_dispatch:

jobs:
  proxyUscrum:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/proxyUscrum/"
          image_import: "images"
          output_dir: "doc/Pdf/proxyUscrum/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: true
          extend_default_theme: true
      - uses: actions/upload-artifact@v2
        with:
          name: "Documentation"
          path: "doc/Pdf/proxyUscrum/"

  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/qualityManager/"
          image_import: "images"
          output_dir: "doc/Pdf/qualityManager/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: true
          extend_default_theme: true
      - uses: actions/upload-artifact@v2
        with:
          name: "Documentation"
          path: "doc/Pdf/qualityManager/"
  doc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: JohnMeyerhoff/markdown-to-pdf@devel
        with:
          input_dir: "doc/"
          image_import: "images"
          output_dir: "doc/Pdf/"
          theme: ".github/workflows/SE.css"
          highlight_theme: ".github/workflows/Codetheme.css"
          table_of_contents: true
          extend_default_theme: true
      - uses: actions/upload-artifact@v2
        with:
          name: "Documentation"
          path: "doc/Pdf/"
